# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_power_supply.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 334)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ch1_volt_dial = QtWidgets.QDial(self.frame)
        self.ch1_volt_dial.setMinimumSize(QtCore.QSize(0, 50))
        self.ch1_volt_dial.setMaximum(300)
        self.ch1_volt_dial.setSingleStep(1)
        self.ch1_volt_dial.setNotchesVisible(False)
        self.ch1_volt_dial.setObjectName("ch1_volt_dial")
        self.horizontalLayout_4.addWidget(self.ch1_volt_dial)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.ch1_volt_lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.ch1_volt_lcdNumber.setObjectName("ch1_volt_lcdNumber")
        self.verticalLayout_5.addWidget(self.ch1_volt_lcdNumber)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.ch1_v_limited_led_label = QtWidgets.QLabel(self.frame)
        self.ch1_v_limited_led_label.setObjectName("ch1_v_limited_led_label")
        self.horizontalLayout_6.addWidget(self.ch1_v_limited_led_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.ch1_v_limited_label = QtWidgets.QLabel(self.frame)
        self.ch1_v_limited_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ch1_v_limited_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_v_limited_label.setObjectName("ch1_v_limited_label")
        self.verticalLayout_7.addWidget(self.ch1_v_limited_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ch1_amps_dial = QtWidgets.QDial(self.frame)
        self.ch1_amps_dial.setMinimumSize(QtCore.QSize(0, 50))
        self.ch1_amps_dial.setMaximum(100)
        self.ch1_amps_dial.setObjectName("ch1_amps_dial")
        self.horizontalLayout_3.addWidget(self.ch1_amps_dial)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.ch1_amps_lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.ch1_amps_lcdNumber.setObjectName("ch1_amps_lcdNumber")
        self.verticalLayout_4.addWidget(self.ch1_amps_lcdNumber)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.ch1_amps_limited_label = QtWidgets.QLabel(self.frame)
        self.ch1_amps_limited_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ch1_amps_limited_label.setObjectName("ch1_amps_limited_label")
        self.horizontalLayout_3.addWidget(self.ch1_amps_limited_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.ch1_activate_pushButton = QtWidgets.QPushButton(self.frame)
        self.ch1_activate_pushButton.setCheckable(True)
        self.ch1_activate_pushButton.setObjectName("ch1_activate_pushButton")
        self.verticalLayout_6.addWidget(self.ch1_activate_pushButton)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ch2_volt_dial = QtWidgets.QDial(self.frame_2)
        self.ch2_volt_dial.setMinimumSize(QtCore.QSize(0, 50))
        self.ch2_volt_dial.setMaximum(300)
        self.ch2_volt_dial.setObjectName("ch2_volt_dial")
        self.horizontalLayout.addWidget(self.ch2_volt_dial)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.ch2_volt_lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.ch2_volt_lcdNumber.setObjectName("ch2_volt_lcdNumber")
        self.verticalLayout.addWidget(self.ch2_volt_lcdNumber)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.ch2_v_limited_radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.ch2_v_limited_radioButton.setCheckable(True)
        self.ch2_v_limited_radioButton.setObjectName("ch2_v_limited_radioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.ch2_v_limited_radioButton)
        self.horizontalLayout.addWidget(self.ch2_v_limited_radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ch2_amps_dial = QtWidgets.QDial(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2_amps_dial.sizePolicy().hasHeightForWidth())
        self.ch2_amps_dial.setSizePolicy(sizePolicy)
        self.ch2_amps_dial.setMinimumSize(QtCore.QSize(0, 50))
        self.ch2_amps_dial.setMaximum(100)
        self.ch2_amps_dial.setObjectName("ch2_amps_dial")
        self.horizontalLayout_2.addWidget(self.ch2_amps_dial)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.ch2_amps_lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.ch2_amps_lcdNumber.setObjectName("ch2_amps_lcdNumber")
        self.verticalLayout_2.addWidget(self.ch2_amps_lcdNumber)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.ch2_amps_limited_radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.ch2_amps_limited_radioButton.setCheckable(True)
        self.ch2_amps_limited_radioButton.setObjectName("ch2_amps_limited_radioButton")
        self.buttonGroup_2.addButton(self.ch2_amps_limited_radioButton)
        self.horizontalLayout_2.addWidget(self.ch2_amps_limited_radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.ch2_activate_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.ch2_activate_pushButton.setCheckable(True)
        self.ch2_activate_pushButton.setObjectName("ch2_activate_pushButton")
        self.verticalLayout_3.addWidget(self.ch2_activate_pushButton)
        self.horizontalLayout_5.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Channel 1"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.ch1_v_limited_led_label.setText(_translate("MainWindow", "        "))
        self.ch1_v_limited_label.setText(_translate("MainWindow", "V limited"))
        self.label_5.setText(_translate("MainWindow", "Current"))
        self.ch1_amps_limited_label.setText(_translate("MainWindow", "I limited"))
        self.ch1_activate_pushButton.setText(_translate("MainWindow", "Activate Output"))
        self.label_2.setText(_translate("MainWindow", "Channel 2"))
        self.label_3.setText(_translate("MainWindow", "Voltage"))
        self.ch2_v_limited_radioButton.setText(_translate("MainWindow", "V &limited"))
        self.label_4.setText(_translate("MainWindow", "Current"))
        self.ch2_amps_limited_radioButton.setText(_translate("MainWindow", "I &limited"))
        self.ch2_activate_pushButton.setText(_translate("MainWindow", "Activate Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

